/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.m3y3r.dupfilefinder.avro;  
@SuppressWarnings("all")
/** hashstring to (file path, file size) index entry */
@org.apache.avro.specific.AvroGenerated
public class HashStringAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HashStringAvro\",\"namespace\":\"de.m3y3r.dupfilefinder.avro\",\"doc\":\"hashstring to (file path, file size) index entry\",\"fields\":[{\"name\":\"hashString\",\"type\":\"string\"},{\"name\":\"filePath\",\"type\":\"string\"},{\"name\":\"fileSize\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence hashString;
  @Deprecated public java.lang.CharSequence filePath;
  @Deprecated public long fileSize;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public HashStringAvro() {}

  /**
   * All-args constructor.
   */
  public HashStringAvro(java.lang.CharSequence hashString, java.lang.CharSequence filePath, java.lang.Long fileSize) {
    this.hashString = hashString;
    this.filePath = filePath;
    this.fileSize = fileSize;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return hashString;
    case 1: return filePath;
    case 2: return fileSize;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: hashString = (java.lang.CharSequence)value$; break;
    case 1: filePath = (java.lang.CharSequence)value$; break;
    case 2: fileSize = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'hashString' field.
   */
  public java.lang.CharSequence getHashString() {
    return hashString;
  }

  /**
   * Sets the value of the 'hashString' field.
   * @param value the value to set.
   */
  public void setHashString(java.lang.CharSequence value) {
    this.hashString = value;
  }

  /**
   * Gets the value of the 'filePath' field.
   */
  public java.lang.CharSequence getFilePath() {
    return filePath;
  }

  /**
   * Sets the value of the 'filePath' field.
   * @param value the value to set.
   */
  public void setFilePath(java.lang.CharSequence value) {
    this.filePath = value;
  }

  /**
   * Gets the value of the 'fileSize' field.
   */
  public java.lang.Long getFileSize() {
    return fileSize;
  }

  /**
   * Sets the value of the 'fileSize' field.
   * @param value the value to set.
   */
  public void setFileSize(java.lang.Long value) {
    this.fileSize = value;
  }

  /** Creates a new HashStringAvro RecordBuilder */
  public static de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder newBuilder() {
    return new de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder();
  }
  
  /** Creates a new HashStringAvro RecordBuilder by copying an existing Builder */
  public static de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder newBuilder(de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder other) {
    return new de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder(other);
  }
  
  /** Creates a new HashStringAvro RecordBuilder by copying an existing HashStringAvro instance */
  public static de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder newBuilder(de.m3y3r.dupfilefinder.avro.HashStringAvro other) {
    return new de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder(other);
  }
  
  /**
   * RecordBuilder for HashStringAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HashStringAvro>
    implements org.apache.avro.data.RecordBuilder<HashStringAvro> {

    private java.lang.CharSequence hashString;
    private java.lang.CharSequence filePath;
    private long fileSize;

    /** Creates a new Builder */
    private Builder() {
      super(de.m3y3r.dupfilefinder.avro.HashStringAvro.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.hashString)) {
        this.hashString = data().deepCopy(fields()[0].schema(), other.hashString);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.filePath)) {
        this.filePath = data().deepCopy(fields()[1].schema(), other.filePath);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.fileSize)) {
        this.fileSize = data().deepCopy(fields()[2].schema(), other.fileSize);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing HashStringAvro instance */
    private Builder(de.m3y3r.dupfilefinder.avro.HashStringAvro other) {
            super(de.m3y3r.dupfilefinder.avro.HashStringAvro.SCHEMA$);
      if (isValidValue(fields()[0], other.hashString)) {
        this.hashString = data().deepCopy(fields()[0].schema(), other.hashString);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.filePath)) {
        this.filePath = data().deepCopy(fields()[1].schema(), other.filePath);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.fileSize)) {
        this.fileSize = data().deepCopy(fields()[2].schema(), other.fileSize);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'hashString' field */
    public java.lang.CharSequence getHashString() {
      return hashString;
    }
    
    /** Sets the value of the 'hashString' field */
    public de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder setHashString(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.hashString = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'hashString' field has been set */
    public boolean hasHashString() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'hashString' field */
    public de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder clearHashString() {
      hashString = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'filePath' field */
    public java.lang.CharSequence getFilePath() {
      return filePath;
    }
    
    /** Sets the value of the 'filePath' field */
    public de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder setFilePath(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.filePath = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'filePath' field has been set */
    public boolean hasFilePath() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'filePath' field */
    public de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder clearFilePath() {
      filePath = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'fileSize' field */
    public java.lang.Long getFileSize() {
      return fileSize;
    }
    
    /** Sets the value of the 'fileSize' field */
    public de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder setFileSize(long value) {
      validate(fields()[2], value);
      this.fileSize = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'fileSize' field has been set */
    public boolean hasFileSize() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'fileSize' field */
    public de.m3y3r.dupfilefinder.avro.HashStringAvro.Builder clearFileSize() {
      fieldSetFlags()[2] = false;
      return this;
    }

//    @Override
    public HashStringAvro build() {
      try {
        HashStringAvro record = new HashStringAvro();
        record.hashString = fieldSetFlags()[0] ? this.hashString : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.filePath = fieldSetFlags()[1] ? this.filePath : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.fileSize = fieldSetFlags()[2] ? this.fileSize : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
